#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Blogger")]
	public partial class DataBloggerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertComment(Comment instance);
    partial void UpdateComment(Comment instance);
    partial void DeleteComment(Comment instance);
    partial void InsertContent(Content instance);
    partial void UpdateContent(Content instance);
    partial void DeleteContent(Content instance);
    partial void InsertKeyIndexBlog(KeyIndexBlog instance);
    partial void UpdateKeyIndexBlog(KeyIndexBlog instance);
    partial void DeleteKeyIndexBlog(KeyIndexBlog instance);
    partial void InsertKeyIndexUser(KeyIndexUser instance);
    partial void UpdateKeyIndexUser(KeyIndexUser instance);
    partial void DeleteKeyIndexUser(KeyIndexUser instance);
    partial void InsertMenu(Menu instance);
    partial void UpdateMenu(Menu instance);
    partial void DeleteMenu(Menu instance);
    partial void InsertMenuAdmin(MenuAdmin instance);
    partial void UpdateMenuAdmin(MenuAdmin instance);
    partial void DeleteMenuAdmin(MenuAdmin instance);
    partial void InsertReaction(Reaction instance);
    partial void UpdateReaction(Reaction instance);
    partial void DeleteReaction(Reaction instance);
    partial void InsertShare(Share instance);
    partial void UpdateShare(Share instance);
    partial void DeleteShare(Share instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertUser_mode(User_mode instance);
    partial void UpdateUser_mode(User_mode instance);
    partial void DeleteUser_mode(User_mode instance);
    partial void InsertSavedContent(SavedContent instance);
    partial void UpdateSavedContent(SavedContent instance);
    partial void DeleteSavedContent(SavedContent instance);
    #endregion
		
		public DataBloggerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BloggerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBloggerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBloggerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBloggerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBloggerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Comment> Comments
		{
			get
			{
				return this.GetTable<Comment>();
			}
		}
		
		public System.Data.Linq.Table<Content> Contents
		{
			get
			{
				return this.GetTable<Content>();
			}
		}
		
		public System.Data.Linq.Table<KeyIndexBlog> KeyIndexBlogs
		{
			get
			{
				return this.GetTable<KeyIndexBlog>();
			}
		}
		
		public System.Data.Linq.Table<KeyIndexUser> KeyIndexUsers
		{
			get
			{
				return this.GetTable<KeyIndexUser>();
			}
		}
		
		public System.Data.Linq.Table<Menu> Menus
		{
			get
			{
				return this.GetTable<Menu>();
			}
		}
		
		public System.Data.Linq.Table<MenuAdmin> MenuAdmins
		{
			get
			{
				return this.GetTable<MenuAdmin>();
			}
		}
		
		public System.Data.Linq.Table<Reaction> Reactions
		{
			get
			{
				return this.GetTable<Reaction>();
			}
		}
		
		public System.Data.Linq.Table<Share> Shares
		{
			get
			{
				return this.GetTable<Share>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<User_mode> User_modes
		{
			get
			{
				return this.GetTable<User_mode>();
			}
		}
		
		public System.Data.Linq.Table<SavedContent> SavedContents
		{
			get
			{
				return this.GetTable<SavedContent>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin
	{
		
		private string _IDAdmin;
		
		private string _AdminName;
		
		private string _Password;
		
		private string _Email;
		
		private string _PhoneNumber;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		public Admin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAdmin", DbType="Char(5)")]
		public string IDAdmin
		{
			get
			{
				return this._IDAdmin;
			}
			set
			{
				if ((this._IDAdmin != value))
				{
					this._IDAdmin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="NVarChar(30)")]
		public string AdminName
		{
			get
			{
				return this._AdminName;
			}
			set
			{
				if ((this._AdminName != value))
				{
					this._AdminName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(30)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Char(10)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comment")]
	public partial class Comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDComment;
		
		private string _IDUser;
		
		private string _UserName;
		
		private string _IDOwner;
		
		private int _IDPost;
		
		private string _CommentString;
		
		private System.DateTime _DateCreated;
		
		private string _IDParent;
		
		private int _Level;
		
		private int _NumChild;
		
		private System.Nullable<System.DateTime> _DateModify;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCommentChanging(int value);
    partial void OnIDCommentChanged();
    partial void OnIDUserChanging(string value);
    partial void OnIDUserChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnIDOwnerChanging(string value);
    partial void OnIDOwnerChanged();
    partial void OnIDPostChanging(int value);
    partial void OnIDPostChanged();
    partial void OnCommentStringChanging(string value);
    partial void OnCommentStringChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnIDParentChanging(string value);
    partial void OnIDParentChanged();
    partial void OnLevelChanging(int value);
    partial void OnLevelChanged();
    partial void OnNumChildChanging(int value);
    partial void OnNumChildChanged();
    partial void OnDateModifyChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifyChanged();
    #endregion
		
		public Comment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDComment", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDComment
		{
			get
			{
				return this._IDComment;
			}
			set
			{
				if ((this._IDComment != value))
				{
					this.OnIDCommentChanging(value);
					this.SendPropertyChanging();
					this._IDComment = value;
					this.SendPropertyChanged("IDComment");
					this.OnIDCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUser", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IDUser
		{
			get
			{
				return this._IDUser;
			}
			set
			{
				if ((this._IDUser != value))
				{
					this.OnIDUserChanging(value);
					this.SendPropertyChanging();
					this._IDUser = value;
					this.SendPropertyChanged("IDUser");
					this.OnIDUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOwner", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IDOwner
		{
			get
			{
				return this._IDOwner;
			}
			set
			{
				if ((this._IDOwner != value))
				{
					this.OnIDOwnerChanging(value);
					this.SendPropertyChanging();
					this._IDOwner = value;
					this.SendPropertyChanged("IDOwner");
					this.OnIDOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPost", DbType="Int NOT NULL")]
		public int IDPost
		{
			get
			{
				return this._IDPost;
			}
			set
			{
				if ((this._IDPost != value))
				{
					this.OnIDPostChanging(value);
					this.SendPropertyChanging();
					this._IDPost = value;
					this.SendPropertyChanged("IDPost");
					this.OnIDPostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentString", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string CommentString
		{
			get
			{
				return this._CommentString;
			}
			set
			{
				if ((this._CommentString != value))
				{
					this.OnCommentStringChanging(value);
					this.SendPropertyChanging();
					this._CommentString = value;
					this.SendPropertyChanged("CommentString");
					this.OnCommentStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDParent", DbType="NChar(10)")]
		public string IDParent
		{
			get
			{
				return this._IDParent;
			}
			set
			{
				if ((this._IDParent != value))
				{
					this.OnIDParentChanging(value);
					this.SendPropertyChanging();
					this._IDParent = value;
					this.SendPropertyChanged("IDParent");
					this.OnIDParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumChild", DbType="Int NOT NULL")]
		public int NumChild
		{
			get
			{
				return this._NumChild;
			}
			set
			{
				if ((this._NumChild != value))
				{
					this.OnNumChildChanging(value);
					this.SendPropertyChanging();
					this._NumChild = value;
					this.SendPropertyChanged("NumChild");
					this.OnNumChildChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModify", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModify
		{
			get
			{
				return this._DateModify;
			}
			set
			{
				if ((this._DateModify != value))
				{
					this.OnDateModifyChanging(value);
					this.SendPropertyChanging();
					this._DateModify = value;
					this.SendPropertyChanged("DateModify");
					this.OnDateModifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Content")]
	public partial class Content : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDUser;
		
		private string _UserName;
		
		private int _IDPost;
		
		private string _Type;
		
		private string _Title;
		
		private string _Contents;
		
		private System.Nullable<int> _HeartCount;
		
		private System.Nullable<int> _CommentCount;
		
		private System.Nullable<int> _SharedCount;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private System.Nullable<System.DateTime> _DateModified;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUserChanging(string value);
    partial void OnIDUserChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnIDPostChanging(int value);
    partial void OnIDPostChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnHeartCountChanging(System.Nullable<int> value);
    partial void OnHeartCountChanged();
    partial void OnCommentCountChanging(System.Nullable<int> value);
    partial void OnCommentCountChanged();
    partial void OnSharedCountChanging(System.Nullable<int> value);
    partial void OnSharedCountChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnDateModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifiedChanged();
    #endregion
		
		public Content()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUser", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDUser
		{
			get
			{
				return this._IDUser;
			}
			set
			{
				if ((this._IDUser != value))
				{
					this.OnIDUserChanging(value);
					this.SendPropertyChanging();
					this._IDUser = value;
					this.SendPropertyChanged("IDUser");
					this.OnIDUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPost", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPost
		{
			get
			{
				return this._IDPost;
			}
			set
			{
				if ((this._IDPost != value))
				{
					this.OnIDPostChanging(value);
					this.SendPropertyChanging();
					this._IDPost = value;
					this.SendPropertyChanged("IDPost");
					this.OnIDPostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(100)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NVarChar(4000)")]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this.OnContentsChanging(value);
					this.SendPropertyChanging();
					this._Contents = value;
					this.SendPropertyChanged("Contents");
					this.OnContentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeartCount", DbType="Int")]
		public System.Nullable<int> HeartCount
		{
			get
			{
				return this._HeartCount;
			}
			set
			{
				if ((this._HeartCount != value))
				{
					this.OnHeartCountChanging(value);
					this.SendPropertyChanging();
					this._HeartCount = value;
					this.SendPropertyChanged("HeartCount");
					this.OnHeartCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentCount", DbType="Int")]
		public System.Nullable<int> CommentCount
		{
			get
			{
				return this._CommentCount;
			}
			set
			{
				if ((this._CommentCount != value))
				{
					this.OnCommentCountChanging(value);
					this.SendPropertyChanging();
					this._CommentCount = value;
					this.SendPropertyChanged("CommentCount");
					this.OnCommentCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SharedCount", DbType="Int")]
		public System.Nullable<int> SharedCount
		{
			get
			{
				return this._SharedCount;
			}
			set
			{
				if ((this._SharedCount != value))
				{
					this.OnSharedCountChanging(value);
					this.SendPropertyChanging();
					this._SharedCount = value;
					this.SendPropertyChanged("SharedCount");
					this.OnSharedCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KeyIndexBlog")]
	public partial class KeyIndexBlog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDKeyIndex;
		
		private int _UserIndex;
		
		private int _AdminIndex;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDKeyIndexChanging(int value);
    partial void OnIDKeyIndexChanged();
    partial void OnUserIndexChanging(int value);
    partial void OnUserIndexChanged();
    partial void OnAdminIndexChanging(int value);
    partial void OnAdminIndexChanged();
    #endregion
		
		public KeyIndexBlog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKeyIndex", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDKeyIndex
		{
			get
			{
				return this._IDKeyIndex;
			}
			set
			{
				if ((this._IDKeyIndex != value))
				{
					this.OnIDKeyIndexChanging(value);
					this.SendPropertyChanging();
					this._IDKeyIndex = value;
					this.SendPropertyChanged("IDKeyIndex");
					this.OnIDKeyIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIndex", DbType="Int NOT NULL")]
		public int UserIndex
		{
			get
			{
				return this._UserIndex;
			}
			set
			{
				if ((this._UserIndex != value))
				{
					this.OnUserIndexChanging(value);
					this.SendPropertyChanging();
					this._UserIndex = value;
					this.SendPropertyChanged("UserIndex");
					this.OnUserIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminIndex", DbType="Int NOT NULL")]
		public int AdminIndex
		{
			get
			{
				return this._AdminIndex;
			}
			set
			{
				if ((this._AdminIndex != value))
				{
					this.OnAdminIndexChanging(value);
					this.SendPropertyChanging();
					this._AdminIndex = value;
					this.SendPropertyChanged("AdminIndex");
					this.OnAdminIndexChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KeyIndexUser")]
	public partial class KeyIndexUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDUser;
		
		private int _IDPost;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUserChanging(string value);
    partial void OnIDUserChanged();
    partial void OnIDPostChanging(int value);
    partial void OnIDPostChanged();
    #endregion
		
		public KeyIndexUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUser", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDUser
		{
			get
			{
				return this._IDUser;
			}
			set
			{
				if ((this._IDUser != value))
				{
					this.OnIDUserChanging(value);
					this.SendPropertyChanging();
					this._IDUser = value;
					this.SendPropertyChanged("IDUser");
					this.OnIDUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPost", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPost
		{
			get
			{
				return this._IDPost;
			}
			set
			{
				if ((this._IDPost != value))
				{
					this.OnIDPostChanging(value);
					this.SendPropertyChanging();
					this._IDPost = value;
					this.SendPropertyChanged("IDPost");
					this.OnIDPostChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
	public partial class Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MenuName;
		
		private string _MenuLink;
		
		private System.Nullable<int> _ParentId;
		
		private System.Nullable<int> _OrderNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMenuNameChanging(string value);
    partial void OnMenuNameChanged();
    partial void OnMenuLinkChanging(string value);
    partial void OnMenuLinkChanged();
    partial void OnParentIdChanging(System.Nullable<int> value);
    partial void OnParentIdChanged();
    partial void OnOrderNumberChanging(System.Nullable<int> value);
    partial void OnOrderNumberChanged();
    #endregion
		
		public Menu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuName", DbType="NVarChar(50)")]
		public string MenuName
		{
			get
			{
				return this._MenuName;
			}
			set
			{
				if ((this._MenuName != value))
				{
					this.OnMenuNameChanging(value);
					this.SendPropertyChanging();
					this._MenuName = value;
					this.SendPropertyChanged("MenuName");
					this.OnMenuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuLink", DbType="NVarChar(100)")]
		public string MenuLink
		{
			get
			{
				return this._MenuLink;
			}
			set
			{
				if ((this._MenuLink != value))
				{
					this.OnMenuLinkChanging(value);
					this.SendPropertyChanging();
					this._MenuLink = value;
					this.SendPropertyChanged("MenuLink");
					this.OnMenuLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int")]
		public System.Nullable<int> ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="Int")]
		public System.Nullable<int> OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuAdmin")]
	public partial class MenuAdmin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MenuName;
		
		private string _MenuLink;
		
		private int _OrderNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMenuNameChanging(string value);
    partial void OnMenuNameChanged();
    partial void OnMenuLinkChanging(string value);
    partial void OnMenuLinkChanged();
    partial void OnOrderNumberChanging(int value);
    partial void OnOrderNumberChanged();
    #endregion
		
		public MenuAdmin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MenuName
		{
			get
			{
				return this._MenuName;
			}
			set
			{
				if ((this._MenuName != value))
				{
					this.OnMenuNameChanging(value);
					this.SendPropertyChanging();
					this._MenuName = value;
					this.SendPropertyChanged("MenuName");
					this.OnMenuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuLink", DbType="VarChar(50)")]
		public string MenuLink
		{
			get
			{
				return this._MenuLink;
			}
			set
			{
				if ((this._MenuLink != value))
				{
					this.OnMenuLinkChanging(value);
					this.SendPropertyChanging();
					this._MenuLink = value;
					this.SendPropertyChanged("MenuLink");
					this.OnMenuLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="Int NOT NULL")]
		public int OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reaction")]
	public partial class Reaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPost;
		
		private string _IDUser;
		
		private string _IDOwner;
		
		private System.Nullable<int> _IsLiked;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPostChanging(int value);
    partial void OnIDPostChanged();
    partial void OnIDUserChanging(string value);
    partial void OnIDUserChanged();
    partial void OnIDOwnerChanging(string value);
    partial void OnIDOwnerChanged();
    partial void OnIsLikedChanging(System.Nullable<int> value);
    partial void OnIsLikedChanged();
    #endregion
		
		public Reaction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPost", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPost
		{
			get
			{
				return this._IDPost;
			}
			set
			{
				if ((this._IDPost != value))
				{
					this.OnIDPostChanging(value);
					this.SendPropertyChanging();
					this._IDPost = value;
					this.SendPropertyChanged("IDPost");
					this.OnIDPostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUser", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDUser
		{
			get
			{
				return this._IDUser;
			}
			set
			{
				if ((this._IDUser != value))
				{
					this.OnIDUserChanging(value);
					this.SendPropertyChanging();
					this._IDUser = value;
					this.SendPropertyChanged("IDUser");
					this.OnIDUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOwner", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDOwner
		{
			get
			{
				return this._IDOwner;
			}
			set
			{
				if ((this._IDOwner != value))
				{
					this.OnIDOwnerChanging(value);
					this.SendPropertyChanging();
					this._IDOwner = value;
					this.SendPropertyChanged("IDOwner");
					this.OnIDOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLiked", DbType="Int")]
		public System.Nullable<int> IsLiked
		{
			get
			{
				return this._IsLiked;
			}
			set
			{
				if ((this._IsLiked != value))
				{
					this.OnIsLikedChanging(value);
					this.SendPropertyChanging();
					this._IsLiked = value;
					this.SendPropertyChanged("IsLiked");
					this.OnIsLikedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shares")]
	public partial class Share : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDUser;
		
		private int _IDUserPost;
		
		private string _IDOwner;
		
		private int _IDPost;
		
		private string _UserName;
		
		private System.DateTime _DateCreated;
		
		private System.DateTime _DateModified;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUserChanging(string value);
    partial void OnIDUserChanged();
    partial void OnIDUserPostChanging(int value);
    partial void OnIDUserPostChanged();
    partial void OnIDOwnerChanging(string value);
    partial void OnIDOwnerChanged();
    partial void OnIDPostChanging(int value);
    partial void OnIDPostChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnDateModifiedChanging(System.DateTime value);
    partial void OnDateModifiedChanged();
    #endregion
		
		public Share()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUser", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDUser
		{
			get
			{
				return this._IDUser;
			}
			set
			{
				if ((this._IDUser != value))
				{
					this.OnIDUserChanging(value);
					this.SendPropertyChanging();
					this._IDUser = value;
					this.SendPropertyChanged("IDUser");
					this.OnIDUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUserPost", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDUserPost
		{
			get
			{
				return this._IDUserPost;
			}
			set
			{
				if ((this._IDUserPost != value))
				{
					this.OnIDUserPostChanging(value);
					this.SendPropertyChanging();
					this._IDUserPost = value;
					this.SendPropertyChanged("IDUserPost");
					this.OnIDUserPostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOwner", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IDOwner
		{
			get
			{
				return this._IDOwner;
			}
			set
			{
				if ((this._IDOwner != value))
				{
					this.OnIDOwnerChanging(value);
					this.SendPropertyChanging();
					this._IDOwner = value;
					this.SendPropertyChanged("IDOwner");
					this.OnIDOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPost", DbType="Int NOT NULL")]
		public int IDPost
		{
			get
			{
				return this._IDPost;
			}
			set
			{
				if ((this._IDPost != value))
				{
					this.OnIDPostChanging(value);
					this.SendPropertyChanging();
					this._IDPost = value;
					this.SendPropertyChanged("IDPost");
					this.OnIDPostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime NOT NULL")]
		public System.DateTime DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDUser;
		
		private string _UserName;
		
		private string _Avatar;
		
		private string _PhoneNumber;
		
		private string _Password;
		
		private string _Sex;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private string _Address;
		
		private string _Degree;
		
		private string _Job;
		
		private string _Facebook;
		
		private string _Instagram;
		
		private string _Youtube;
		
		private string _LinkedIn;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private System.Nullable<System.DateTime> _DateModify;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUserChanging(string value);
    partial void OnIDUserChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnAvatarChanging(string value);
    partial void OnAvatarChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnDegreeChanging(string value);
    partial void OnDegreeChanged();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnFacebookChanging(string value);
    partial void OnFacebookChanged();
    partial void OnInstagramChanging(string value);
    partial void OnInstagramChanged();
    partial void OnYoutubeChanging(string value);
    partial void OnYoutubeChanged();
    partial void OnLinkedInChanging(string value);
    partial void OnLinkedInChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnDateModifyChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifyChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUser", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDUser
		{
			get
			{
				return this._IDUser;
			}
			set
			{
				if ((this._IDUser != value))
				{
					this.OnIDUserChanging(value);
					this.SendPropertyChanging();
					this._IDUser = value;
					this.SendPropertyChanged("IDUser");
					this.OnIDUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="VarChar(50)")]
		public string Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="Date")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this.OnBirthdayChanging(value);
					this.SendPropertyChanging();
					this._Birthday = value;
					this.SendPropertyChanged("Birthday");
					this.OnBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degree", DbType="NVarChar(100)")]
		public string Degree
		{
			get
			{
				return this._Degree;
			}
			set
			{
				if ((this._Degree != value))
				{
					this.OnDegreeChanging(value);
					this.SendPropertyChanging();
					this._Degree = value;
					this.SendPropertyChanged("Degree");
					this.OnDegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="NVarChar(100)")]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facebook", DbType="VarChar(50)")]
		public string Facebook
		{
			get
			{
				return this._Facebook;
			}
			set
			{
				if ((this._Facebook != value))
				{
					this.OnFacebookChanging(value);
					this.SendPropertyChanging();
					this._Facebook = value;
					this.SendPropertyChanged("Facebook");
					this.OnFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instagram", DbType="VarChar(50)")]
		public string Instagram
		{
			get
			{
				return this._Instagram;
			}
			set
			{
				if ((this._Instagram != value))
				{
					this.OnInstagramChanging(value);
					this.SendPropertyChanging();
					this._Instagram = value;
					this.SendPropertyChanged("Instagram");
					this.OnInstagramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Youtube", DbType="VarChar(50)")]
		public string Youtube
		{
			get
			{
				return this._Youtube;
			}
			set
			{
				if ((this._Youtube != value))
				{
					this.OnYoutubeChanging(value);
					this.SendPropertyChanging();
					this._Youtube = value;
					this.SendPropertyChanged("Youtube");
					this.OnYoutubeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkedIn", DbType="NVarChar(50)")]
		public string LinkedIn
		{
			get
			{
				return this._LinkedIn;
			}
			set
			{
				if ((this._LinkedIn != value))
				{
					this.OnLinkedInChanging(value);
					this.SendPropertyChanging();
					this._LinkedIn = value;
					this.SendPropertyChanged("LinkedIn");
					this.OnLinkedInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModify", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModify
		{
			get
			{
				return this._DateModify;
			}
			set
			{
				if ((this._DateModify != value))
				{
					this.OnDateModifyChanging(value);
					this.SendPropertyChanging();
					this._DateModify = value;
					this.SendPropertyChanged("DateModify");
					this.OnDateModifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_mode")]
	public partial class User_mode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDUser;
		
		private bool _UserNameMode;
		
		private bool _PhoneNumberMode;
		
		private bool _SexMode;
		
		private bool _EmailMode;
		
		private bool _BirthdayMode;
		
		private bool _AddressMode;
		
		private bool _DegreeMode;
		
		private bool _JobMode;
		
		private bool _FacebookMode;
		
		private bool _InstagramMode;
		
		private bool _YoutubeMode;
		
		private bool _LinkedInMode;
		
		private System.Nullable<System.DateTime> _DateModify;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUserChanging(string value);
    partial void OnIDUserChanged();
    partial void OnUserNameModeChanging(bool value);
    partial void OnUserNameModeChanged();
    partial void OnPhoneNumberModeChanging(bool value);
    partial void OnPhoneNumberModeChanged();
    partial void OnSexModeChanging(bool value);
    partial void OnSexModeChanged();
    partial void OnEmailModeChanging(bool value);
    partial void OnEmailModeChanged();
    partial void OnBirthdayModeChanging(bool value);
    partial void OnBirthdayModeChanged();
    partial void OnAddressModeChanging(bool value);
    partial void OnAddressModeChanged();
    partial void OnDegreeModeChanging(bool value);
    partial void OnDegreeModeChanged();
    partial void OnJobModeChanging(bool value);
    partial void OnJobModeChanged();
    partial void OnFacebookModeChanging(bool value);
    partial void OnFacebookModeChanged();
    partial void OnInstagramModeChanging(bool value);
    partial void OnInstagramModeChanged();
    partial void OnYoutubeModeChanging(bool value);
    partial void OnYoutubeModeChanged();
    partial void OnLinkedInModeChanging(bool value);
    partial void OnLinkedInModeChanged();
    partial void OnDateModifyChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifyChanged();
    #endregion
		
		public User_mode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUser", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDUser
		{
			get
			{
				return this._IDUser;
			}
			set
			{
				if ((this._IDUser != value))
				{
					this.OnIDUserChanging(value);
					this.SendPropertyChanging();
					this._IDUser = value;
					this.SendPropertyChanged("IDUser");
					this.OnIDUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameMode", DbType="Bit NOT NULL")]
		public bool UserNameMode
		{
			get
			{
				return this._UserNameMode;
			}
			set
			{
				if ((this._UserNameMode != value))
				{
					this.OnUserNameModeChanging(value);
					this.SendPropertyChanging();
					this._UserNameMode = value;
					this.SendPropertyChanged("UserNameMode");
					this.OnUserNameModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumberMode", DbType="Bit NOT NULL")]
		public bool PhoneNumberMode
		{
			get
			{
				return this._PhoneNumberMode;
			}
			set
			{
				if ((this._PhoneNumberMode != value))
				{
					this.OnPhoneNumberModeChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumberMode = value;
					this.SendPropertyChanged("PhoneNumberMode");
					this.OnPhoneNumberModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexMode", DbType="Bit NOT NULL")]
		public bool SexMode
		{
			get
			{
				return this._SexMode;
			}
			set
			{
				if ((this._SexMode != value))
				{
					this.OnSexModeChanging(value);
					this.SendPropertyChanging();
					this._SexMode = value;
					this.SendPropertyChanged("SexMode");
					this.OnSexModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailMode", DbType="Bit NOT NULL")]
		public bool EmailMode
		{
			get
			{
				return this._EmailMode;
			}
			set
			{
				if ((this._EmailMode != value))
				{
					this.OnEmailModeChanging(value);
					this.SendPropertyChanging();
					this._EmailMode = value;
					this.SendPropertyChanged("EmailMode");
					this.OnEmailModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthdayMode", DbType="Bit NOT NULL")]
		public bool BirthdayMode
		{
			get
			{
				return this._BirthdayMode;
			}
			set
			{
				if ((this._BirthdayMode != value))
				{
					this.OnBirthdayModeChanging(value);
					this.SendPropertyChanging();
					this._BirthdayMode = value;
					this.SendPropertyChanged("BirthdayMode");
					this.OnBirthdayModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressMode", DbType="Bit NOT NULL")]
		public bool AddressMode
		{
			get
			{
				return this._AddressMode;
			}
			set
			{
				if ((this._AddressMode != value))
				{
					this.OnAddressModeChanging(value);
					this.SendPropertyChanging();
					this._AddressMode = value;
					this.SendPropertyChanged("AddressMode");
					this.OnAddressModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DegreeMode", DbType="Bit NOT NULL")]
		public bool DegreeMode
		{
			get
			{
				return this._DegreeMode;
			}
			set
			{
				if ((this._DegreeMode != value))
				{
					this.OnDegreeModeChanging(value);
					this.SendPropertyChanging();
					this._DegreeMode = value;
					this.SendPropertyChanged("DegreeMode");
					this.OnDegreeModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobMode", DbType="Bit NOT NULL")]
		public bool JobMode
		{
			get
			{
				return this._JobMode;
			}
			set
			{
				if ((this._JobMode != value))
				{
					this.OnJobModeChanging(value);
					this.SendPropertyChanging();
					this._JobMode = value;
					this.SendPropertyChanged("JobMode");
					this.OnJobModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacebookMode", DbType="Bit NOT NULL")]
		public bool FacebookMode
		{
			get
			{
				return this._FacebookMode;
			}
			set
			{
				if ((this._FacebookMode != value))
				{
					this.OnFacebookModeChanging(value);
					this.SendPropertyChanging();
					this._FacebookMode = value;
					this.SendPropertyChanged("FacebookMode");
					this.OnFacebookModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstagramMode", DbType="Bit NOT NULL")]
		public bool InstagramMode
		{
			get
			{
				return this._InstagramMode;
			}
			set
			{
				if ((this._InstagramMode != value))
				{
					this.OnInstagramModeChanging(value);
					this.SendPropertyChanging();
					this._InstagramMode = value;
					this.SendPropertyChanged("InstagramMode");
					this.OnInstagramModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoutubeMode", DbType="Bit NOT NULL")]
		public bool YoutubeMode
		{
			get
			{
				return this._YoutubeMode;
			}
			set
			{
				if ((this._YoutubeMode != value))
				{
					this.OnYoutubeModeChanging(value);
					this.SendPropertyChanging();
					this._YoutubeMode = value;
					this.SendPropertyChanged("YoutubeMode");
					this.OnYoutubeModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkedInMode", DbType="Bit NOT NULL")]
		public bool LinkedInMode
		{
			get
			{
				return this._LinkedInMode;
			}
			set
			{
				if ((this._LinkedInMode != value))
				{
					this.OnLinkedInModeChanging(value);
					this.SendPropertyChanging();
					this._LinkedInMode = value;
					this.SendPropertyChanged("LinkedInMode");
					this.OnLinkedInModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModify", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModify
		{
			get
			{
				return this._DateModify;
			}
			set
			{
				if ((this._DateModify != value))
				{
					this.OnDateModifyChanging(value);
					this.SendPropertyChanging();
					this._DateModify = value;
					this.SendPropertyChanged("DateModify");
					this.OnDateModifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SavedContent")]
	public partial class SavedContent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDUser;
		
		private string _IDOwner;
		
		private int _IDPost;
		
		private System.DateTime _DateCreated;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUserChanging(string value);
    partial void OnIDUserChanged();
    partial void OnIDOwnerChanging(string value);
    partial void OnIDOwnerChanged();
    partial void OnIDPostChanging(int value);
    partial void OnIDPostChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    #endregion
		
		public SavedContent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUser", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDUser
		{
			get
			{
				return this._IDUser;
			}
			set
			{
				if ((this._IDUser != value))
				{
					this.OnIDUserChanging(value);
					this.SendPropertyChanging();
					this._IDUser = value;
					this.SendPropertyChanged("IDUser");
					this.OnIDUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOwner", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDOwner
		{
			get
			{
				return this._IDOwner;
			}
			set
			{
				if ((this._IDOwner != value))
				{
					this.OnIDOwnerChanging(value);
					this.SendPropertyChanging();
					this._IDOwner = value;
					this.SendPropertyChanged("IDOwner");
					this.OnIDOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPost", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPost
		{
			get
			{
				return this._IDPost;
			}
			set
			{
				if ((this._IDPost != value))
				{
					this.OnIDPostChanging(value);
					this.SendPropertyChanging();
					this._IDPost = value;
					this.SendPropertyChanged("IDPost");
					this.OnIDPostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
